### ISSUE TITLE
parallel-netcdf 1.12.x doesn't build with latest Intel oneAPI compilers (incl. classic) on Cheyenne

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack#15]
### Steps to reproduce

For parallel-netcdf, one needs to substitute `I_MPI_SUBSTITUTE_DIR` with `I_MPI_ROOT`. The issue is that the spack compiler wrappers don't set `I_MPI_ROOT` when building parallel-netcdf, and on systems where the sysadmins did not search-and-replace `I_MPI_SUBSTITUTE_DIR` in the MPI compiler wrappers (for example, on Cheyenne), this leads to a problem. Note that the spack install of intel-oneapi-mpi does replace those after installation, and on many systems the sysadmins do that manually as well, but we can't rely on it.
```
cat /glade/u/apps/opt/intel/2021.2/mpi/latest/bin/mpif90
...
# Directory locations: Fixed for any MPI implementation.
# Set from the directory arguments to configure (e.g., --prefix=/usr/local)
prefix=I_MPI_SUBSTITUTE_INSTALLDIR
# The environment variable I_MPI_ROOT may be used to override installation folder path
if [ -n "$I_MPI_ROOT" ] ; then
    prefix=$I_MPI_ROOT;
fi

exec_prefix=__EXEC_PREFIX_TO_BE_FILLED_AT_INSTALL_TIME__
sysconfdir=${prefix}/etc
includedir=${prefix}/include
libdir=${prefix}/lib
...
```

### Error message

n.n.

### Information on your system

n.n.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by kgerheiser** [comment]
Why does the I_MPI_ROOT thing affect only pnetcdf? What is the error message you get?

**Comment by climbfuji** [comment]
The wrapper is not substituting `I_MPI_SUBSTITUTE_DIR` and therefore you get a compile/link command like this:
```
mpifc ... -L I_MPI_SUBSTITUTE_DIR/lib ...
```
I was also wondering why only parallel-netcdf, therefore I put the bugfix just in that package. See `spack/var/spack/repos/builtin/packages/intel-oneapi-mpi/package.py` for the note in the intel-oneapi-mpi package.

**Comment by climbfuji** [comment]
One difference is that parallel-netcdf is an autotools package, whereas most others are cmake packages (all others that we use?).

**Comment by kgerheiser** [comment]
Can you show the `prefix` entry in your `packages.yaml` for `intel-oneapi-mpi`? The issue, I believe, is that rather than using the MPI wrappers directly, it uses `--with-mpi=<prefix>`. But the `prefix` for `intel-oneapi-mpi` is `/opt/intel/oneapi`, instead of `/opt/intel/oneapi/mpi/..../bin`. And this is due to how the `IntelOneAPI` build class is designed. It uses that top-level prefix for MPI, MKL, etc.

**Comment by kgerheiser** [comment]
I ran into what i think is the same issue with Nemsio, which uses `target_link_libraries(MPI::MPI_Fortran)`. CMake couldn't find MPI because the prefix set in `CMAKE_PREFIX_PATH` was `/opt/intel` while CMake expects the directory containing `bin`.

**Comment by climbfuji** [comment]
The prefix is `/glade/u/apps/opt/intel/2021.2`  so yes, that's the same I suppose.

**Comment by climbfuji** [comment]
Either way there needs to be a patch in the parallel-netcdf package.py ... whether that's setting `I_MPI_ROOT` or the following variables. I think that might work as well.
```
  MPICC       MPI C compiler, [default: CC]
  MPICXX      MPI C++ compiler, [default: CXX]
  MPIF77      MPI Fortran 77 compiler, [default: F77]
  MPIF90      MPI Fortran 90 compiler, [default: FC]
```

**Comment by kgerheiser** [comment]
I have to look at the build options for pnetcdf, but it might be better to set pnetcdf to use the compiler wrappers for CC, FC.

**Comment by climbfuji** [comment]
I can try that quickly ...

**Comment by kgerheiser** [comment]
The syntax is `spec['mpi'].mpicc` (stolen from HDF5).

**Comment by climbfuji** [comment]
> The syntax is `spec['mpi'].mpicc` (stolen from HDF5).

I had the same idea  ;-)

**Comment by climbfuji** [comment]
Both of these methods don't work, same error.
```
    def configure_args(self):
        args = ['--with-mpi=%s' % self.spec['mpi'].prefix,
                'SEQ_CC=%s' % spack_cc]

        args += self.enable_or_disable('cxx')
        args += self.enable_or_disable('fortran')

        flags = {
            'CFLAGS': [],
            'CXXFLAGS': [],
            'FFLAGS': [],
            'FCFLAGS': [],
            'MPICC': [self.spec['mpi'].mpicc],
            'MPICXX': [self.spec['mpi'].mpicxx],
            'MPIF77': [self.spec['mpi'].mpifc],
            'MPIF90': [self.spec['mpi'].mpifc],
        }
```
and
```
    def setup_build_environment(self, env):
        env.set('MPICC',  self.spec['mpi'].mpicc)
        env.set('MPICXX', self.spec['mpi'].mpicxx)
        env.set('MPIF77', self.spec['mpi'].mpifc)
        env.set('MPIF90', self.spec['mpi'].mpifc)
```

**Comment by kgerheiser** [comment]
Using `setup_build_environment` and removing the `--with-mpi=` worked for me. One thing I would check is that the `intel-oneapi-mpi` version matches the version in the MPI path. Like, 

```bash
parallels@parallels-Parallels-Virtual-Platform:~/Desktop/spack-stack/envs/all.default$ which mpicc
/opt/intel/oneapi/mpi/2021.5.1//bin/mpicc
```

My spec was `2021.5`, instead of `2021.5.1`. The version is used to construct the path.

This is the error I was getting.

```
1 error found in build log:
     14    checking for gawk... (cached) mawk
     15    checking for grep that handles long lines and -e... /usr/bin/grep
     16    checking for egrep... /usr/bin/grep -E
     17    checking for a sed that does not truncate output... /usr/bin/sed
     18    checking for sed handling option -i ... /usr/bin/sed -i''
     19    checking whether /opt/intel/oneapi/mpi/2021.5/bin/mpicc exists and is executable... no
  >> 20    configure: error:
     21       -----------------------------------------------------------------------
     22         Specified MPI C compiler "/opt/intel/oneapi/bin/mpicc" cannot be found
     23         PnetCDF requires a working MPI C compiler. Please specify the location
     24         of an MPI C compiler, either in the MPICC environment variable
     25         (not CC variable) or through --with-mpi configure flag. Abort.
     26       -----------------------------------------------------------------------
```

Then, I added `setup_build_environment` with your code. A tip is to throw a `print(self.spec['mpi'].mpicc)` and use `spack install -v`.

**Comment by climbfuji** [comment]
The path/spec was correct, the configure step went through just fine and I got the same problem as before, namely that in the ./configure step is looking for -LI_MPI_SUBSTITUTE_DIR/lib etc. It then continues just fine and fails during the make step.

I think you will have to try to reproduce this on Cheyenne, everything is done differently there.

**Comment by kgerheiser** [comment]
I actually just noticed I get the same thing while it runs configure.

```
checking for Fortran libraries of /opt/intel/oneapi/mpi/2021.5.1/bin/mpifc...  -LI_MPI_SUBSTITUTE_INSTALLDIR/lib/release -LI_MPI_SUBSTITUTE_INSTALLDIR/lib..........
```

But it doesn't throw an error.


I'm fine with merging the PR to move things along, but I wonder if there's a better solution.

**Comment by climbfuji** [comment]
That's really weird. I got many more problems on Cheyenne today, code that compiled previously doesn't compile anymore etc. I agree that there must be a better solution, but given that the intel-oneapi-mpi install in spack explicitly substitutes those I_MPI_SUBSTITUTE and `_EXEC_PREFIX_TO_BE_FILLED_AT_INSTALL_TIME__` dirs it might not be that easy.

That brings up an interesting question. On Cheyenne `_EXEC_PREFIX_TO_BE_FILLED_AT_INSTALL_TIME__` is not replaced during the installation. How about your installation?

**Comment by kgerheiser** [comment]
Nope, my vanilla install on a generic Ubuntu VM contains `exec_prefix=__EXEC_PREFIX_TO_BE_FILLED_AT_INSTALL_TIME__`

Maybe a bug with the installer? Or because it's installed with APT instead of their installer?

**Comment by climbfuji** [comment]
I'll try again tomorrow with the method that worked for you, just to be sure. If it still doesn't work, then let's use the I_MPI_ROOT trick.

**Comment by kgerheiser** [comment]
Oh hey, I'm getting the same error with the Intel workflow with ncio.

https://github.com/kgerheiser/spack-stack/runs/5308785967?check_suite_focus=true

```
...I_MPI_SUBSTITUTE_INSTALLDIR/include"
n its INTERFACE_INCLUDE_DIRECTORIES.
```

**Comment by kgerheiser** [comment]
I posted this on the Intel community forums: https://community.intel.com/t5/Intel-oneAPI-HPC-Toolkit/I-MPI-SUBSTITUTE-INSTALLDIR/m-p/1363427#M9210

**Comment by climbfuji** [comment]
Ok, let's merge the solution we have now but I'll keep this issue open just in case a better solution is provided.

**Comment by climbfuji** [comment]
The issue with `I_MPI_SUBSTITUTE_INSTALL_DIR` is much more widespread. I just looked at some of the build logs, it's in the eckit, fckit, .. everywhere. It doesn't hurt but it's not ideal to have this underlying bug.

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack/pull/13
