### ISSUE TITLE
Unit tests fail because of module hash check

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack#151]
### Steps to reproduce

See https://github.com/NOAA-EMC/spack/runs/7694783875?check_suite_focus=true

```
>       assert service_part in path_parts
410
E       AssertionError: assert 'mpich/3.0.4-d7mxhy7' in ['mpich/3.0.4', 'Core']
```

A hash is expected in the module name, but there is only the version.

I think this is related to some change that was made somewhere inside of Spack about LMod modules always having a hash.

### Information on your system

n/a

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by climbfuji** [comment]
I think this is more a bug on the unit testing side (in our fork) now that we built in the capability to shorten the module name hashes or omit them entirely.

**Comment by climbfuji** [comment]
Closed via #https://github.com/NOAA-EMC/spack/pull/188
