### ISSUE TITLE
requesting updates to package.py for CRTM

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/spack#155]
@climbfuji 

https://github.com/NOAA-EMC/spack/blob/8a949c880aac1781852eb8c1ef45f32668edcdfb/var/spack/repos/builtin/packages/crtm/package.py

Here are the relevant tags for CRTM (https://github.com/JCSDA/crtm):
For JEDI use:
`v2.4_jedi`     ( tag newly created, points to `release/crtm_jedi_v2.4.0`)
`v2.3_jedi.4`  ( points to `release/crtm_jedi`  last digit incremented with updates to the release branch) 

For EMC use:
`v2.4.0_emc`   ( tag newly created, points to `release/REL-2.4.0_emc` )
`v2.3.0_emc`   ( tag newly created, points to `release/REL-2.3.0_emc` ) 

EMC releases use `git-lfs` for the binary `fix/` directory, but an alternative exists for systems with no `git-lfs` support.

jedi releases rely on `ctest` to download fix/ coefficients from GDEX.    This download should probably occur during the build process, rather than the ctest. 

This is all that `spack-stack` needs to support right now.   The  "non-EMC" and "non-jedi" releases of CRTM do not need to be in `spack stack`.

**Comment by climbfuji** [comment]
Thanks, @BenjaminTJohnson - I'll work on this in the afternoon.
