### ISSUE TITLE
mapl depends on cmake, but dependency is not in package.py

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack#165]
### Steps to reproduce

mapl depends on cmake, but there is no dependency in the package.py file.

Specifically, mapl@2.22 depends on cmake@3.17 or later. Given that cmake nowadays is somewhere around 3.23, it makes sense to simply ask for cmake@3.17, regardless of the mapl version

### Error message

n/a

### Information on your system

n/a

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by mathomp4** [comment]
> Specifically, mapl@2.22 depends on cmake@3.17 or later. Given that cmake nowadays is somewhere around 3.23, it makes sense to simply ask for cmake@3.17, regardless of the mapl version

Note that I think CMake 3.17 is enough. Technically some optional build methods of MAPL (CMake Presets) require 3.21, but I've been hesitant to update the required version since I'm not sure if all systems have it. 

Good thing about spack-stack, probably never find something as old as CMake 3.17 in it! :)

**Comment by climbfuji** [comment]
> > Specifically, mapl@2.22 depends on cmake@3.17 or later. Given that cmake nowadays is somewhere around 3.23, it makes sense to simply ask for cmake@3.17, regardless of the mapl version
> 
> Note that I think CMake 3.17 is enough. Technically some optional build methods of MAPL (CMake Presets) require 3.21, but I've been hesitant to update the required version since I'm not sure if all systems have it.
> 
> Good thing about spack-stack, probably never find something as old as CMake 3.17 in it! :)

That's right. Without the dependency in the recipe it finds the default cmake - which on some older systems can be as "recent" as 3.16 ...
