### ISSUE TITLE
Installation issue: crtm-fix

### ISSUE THREAD

**Issue by rickgrubin** [JCSDA/spack#194]
### Steps to reproduce the issue

```console
spack spec -I crtm-fix
Input spec
--------------------------------
 -   crtm-fix

Concretized
--------------------------------
 -   crtm-fix@2.4.0_emc%intel@18.0.3~big_endian+little_endian+netcdf build_system=generic arch=linux-rhel7-broadwell
```

```
% spack env create crtm-fix
==> Created environment 'crtm-fix'
==> You can activate this environment with:
==>   spack env activate crtm-fix
% spack env activate crtm-fix
% spack add crtm-fix@2.4.0_emc +little_endian ~big_endian
==> Adding crtm-fix@2.4.0_emc~big_endian+little_endian to environment crtm-fix
% spack install
==> Installing environment crtm-fix
==> Installing crtm-fix-2.4.0_emc-4tu7bfryh3yevob62zv4zrjnsz4nbl2s
==> No binary for crtm-fix-2.4.0_emc-4tu7bfryh3yevob62zv4zrjnsz4nbl2s found: installing from source
==> Fetching ftp://ftp.ucar.edu/pub/cpaess/bjohns/fix_REL-2.4.0_emc.tgz
==> No patches needed for crtm-fix
==> crtm-fix: Executing phase: 'install'
==> Error: IsADirectoryError: [Errno 21] Is a directory: '/tmp/grubin/spack-stage/spack-stage-crtm-fix-2.4.0_emc-4tu7bfryh3yevob62zv4zrjnsz4nbl2s/spack-src/fix/J2_CRTM_Coeff_Oct31_2022/Little_Endian/from_J1'

/fs/scratch/essscratch/PYS0343/grubin/src/spire-spack/spack/var/spack/repos/builtin/packages/crtm-fix/package.py:73, in install:
         70                    join_path(self.prefix.fix, "amsua_metop-c.SpcCoeff.bin"))
         71
         72        for f in fix_files:
  >>     73            install(f, self.prefix.fix)

See build log for details
```

Please note that this will only work as noted above after changing the currently incorrect `sha256` checksum in `crtm-fix/package.py` with a correct checksum, as noted below.

### Error message

<details><summary>Error message</summary><pre>
==> [timestamp] Installing /path/to/spack/cache/build_stage/spack-stage-crtm-fix-2.4.0_emc-4tu7bfryh3yevob62zv4zrjnsz4nbl2s/spack-src/fix/J2_CRTM_Coeff_Oct31_2022/Little_Endian/from_J1 to /path/to/spack/env/install/intel/18.0.3/crtm-fix-2.4.0_emc-4tu7bfr/fix
==> Error: IsADirectoryError: [Errno 21] Is a directory: '/path/to/spack/cache/build_stage/spack-stage-crtm-fix-2.4.0_emc-4tu7bfryh3yevob62zv4zrjnsz4nbl2s/spack-src/fix/J2_CRTM_Coeff_Oct31_2022/Little_Endian/from_J1'

/path/to/spack/var/spack/repos/builtin/packages/crtm-fix/package.py:73, in install:

         70                    join_path(self.prefix.fix, "amsua_metop-c.SpcCoeff.bin"))
         71
         72        for f in fix_files:
         73            install(f, self.prefix.fix)
</pre></details>

==> [timestamp] Installing /path/to/spack/cache/build_stage/spack-stage-crtm-fix-2.4.0_emc-4tu7bfryh3yevob62zv4zrjnsz4nbl2s/spack-src/fix/J2_CRTM_Coeff_Oct31_2022/Little_Endian/from_J1 to /path/to/spack/env/install/intel/18.0.3/crtm-fix-2.4.0_emc-4tu7bfr/fix
==> Error: IsADirectoryError: [Errno 21] Is a directory: '/path/to/spack/cache/build_stage/spack-stage-crtm-fix-2.4.0_emc-4tu7bfryh3yevob62zv4zrjnsz4nbl2s/spack-src/fix/J2_CRTM_Coeff_Oct31_2022/Little_Endian/from_J1'

/path/to/spack/var/spack/repos/builtin/packages/crtm-fix/package.py:73, in install:

         70                    join_path(self.prefix.fix, "amsua_metop-c.SpcCoeff.bin"))
         71
         72        for f in fix_files:
         73            install(f, self.prefix.fix)

### Information on your system

spack debug report
* **Spack:** 0.19.0.dev0 (8cd99939daedbf331e99f61f8a46a6eb6cdfd1b1)
* **Python:** 3.9.13
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

[spack-build-out.txt](https://github.com/NOAA-EMC/spack/files/9993637/spack-build-out.txt)
[spack-build-env.txt](https://github.com/NOAA-EMC/spack/files/9993650/spack-build-env.txt)

### Additional information

@kgerheiser @climbfuji 

[https://github.com/NOAA-EMC/spack/blob/jcsda_emc_spack_stack/var/spack/repos/builtin/packages/crtm-fix/package.py](https://github.com/NOAA-EMC/spack/blob/jcsda_emc_spack_stack/var/spack/repos/builtin/packages/crtm-fix/package.py)

fix files are available at: [ftp://ftp.ucar.edu/pub/cpaess/bjohns/fix_REL-{2.3.0, 2.4.0}_emc.tgz](url)

Error 1:

**v2.4.0_emc** introduces a new directory into the fix file hierarchy: `J2_CRTM_Coeff_Oct31_2022`

```
% ls -FCa crtm-internal_REL-2.4.0_emc/fix
./  ../  ACCoeff/  AerosolCoeff/  CloudCoeff/  EmisCoeff/  J2_CRTM_Coeff_Oct31_2022/  SpcCoeff/  TauCoeff/
```

Within this directory's `{BigEndian, LittleEndian, netCDF}` subdirectories are fix files, but also a subdirectory: `from_J1`, e.g.:

```
% pwd
/path/to/crtm-internal_REL-2.4.0_emc/fix/J2_CRTM_Coeff_Oct31_2022/Little_Endian
% ls -d */
from_J1/
```

There are no subdirectories present in the **v2.3.0_emc** `/path/to/type-of-fix-file/{BigEndian, LittleEndian, netCDF}` hierarchy; there are only `fix` files.

When collecting a list of fix files via:

```
        fix_files = []
        for d in endian_dirs:
            fix_files = fix_files + find(".", "*/{}/*".format(d))
```

`fix_files` will thus contain `fix/J2_CRTM_Coeff_Oct31_2022/{BigEndian, LittleEndian, netCDF}/from_J1` 

When attempting to execute:

```
        for f in fix_files:
            install(f, self.prefix.fix)
```

failure occurs because `from_J1` is a directory, and not a regular file.

Error 2:

The checksum for [ftp://ftp.ucar.edu/pub/cpaess/bjohns/fix_REL-2.4.0_emc.tgz](url) should be:

`sha256="04dc8666c66e5ec2b15a03990ad6a20dc023c2dc5f5e1b805d6dd1e3ca2ea4ef"`

instead of

`sha256="84b176ee16cce0897377696cc4f621ef5a55cae7ea8280a0acd5ff70d4435995`

```
% wget ftp://ftp.ucar.edu/pub/cpaess/bjohns/fix_REL-2.4.0_emc.tgz
% shasum -a 256 fix_REL-2.4.0_emc.tgz 
04dc8666c66e5ec2b15a03990ad6a20dc023c2dc5f5e1b805d6dd1e3ca2ea4ef  fix_REL-2.4.0_emc.tgz
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by climbfuji** [comment]
Thanks for reporting this error, @rickgrubin . I wonder what happened. When @kgerheiser added this package, the hash and the logic worked. But since the `+fix` variant is `false` by default, it's not tested regularly. @BenjaminTJohnson are you aware of any updates of the fix files for EMC in the last 6-12 months?

**Comment by rickgrubin** [comment]
With respect to the [ crtm 2.4.0_emc tag](https://github.com/JCSDA/crtm/tree/release/REL-2.4.0_emc), this commit:

[adding JPSS-2 coefficient files from JCSDA and STAR](https://github.com/JCSDA/crtm/commit/4a761ca3b29481153aa5ac811d0da1c856bac6cb)

added the files in question. It appears that commit was made after the tagged release; perhaps these fix files were picked up and added to `ftp://ftp.ucar.edu/pub/cpaess/bjohns/fix_REL-2.4.0_emc.tgz` ?

The `fix/` directory included with [ crtm 2.4.0_emc ](https://github.com/JCSDA/crtm/tree/release/REL-2.4.0_emc) do not include the directory / files in question, is that a disconnect? Should the `crtm-fix` zipped tarball match the `fix/` directory available in the tagged release (and not include the files added in the aforementioned commit)? 

Given that the commit noted above introduced these files, and isn't part of the tagged release nor part of the `develop` branch, should the tagged release contain the `fix/` directory at all?

**Comment by BenjaminTJohnson** [comment]
Those were added as a convenience for some of the EMC researchers who were asking for the files, I think I can safely remove those directories.

My question for you: do you use the fix directory that's in the repository, or the fix directory that's in the tarball?

**Comment by rickgrubin** [comment]
The [NOAA-EMC/spack](https://github.com/NOAA-EMC/spack) package for [crtm @2.4.0_emc](https://github.com/JCSDA/crtm/tree/release/REL-2.4.0_emchttps://github.com/JCSDA/crtm/tree/release/REL-2.4.0_emc) wants to add `fix` files from `ftp://ftp.ucar.edu/pub/cpaess/bjohns/fix_REL-2.4.0_emc.tgz` when the `+fix` variant is specified; the resultant `spack crtm-fix` package fails -- thus this bug report. 

Either the `crtm-fix/package.py` file requires correction, or `ftp://ftp.ucar.edu/pub/cpaess/bjohns/fix_REL-2.4.0_emc.tgz` should not include the fix files added for EMC researchers per your comment; based on the comment, modifying `ftp://ftp.ucar.edu/pub/cpaess/bjohns/fix_REL-2.4.0_emc.tgz` to not include those files, and updating the `spack checksum` for said zipped tarball is the path of least resistance.

To your question: If the `fix/` directory in the tagged release is the same as the zipped tarball, it wouldn't matter which set is chosen -- short of comparing each file individually, are they the same? It seems that `crtm@2.4.0_emc/fix` should be identical to `ftp://ftp.ucar.edu/pub/cpaess/bjohns/fix_REL-2.4.0_emc.tgz`, based solely on naming scheme. It would be helpful to know.

I could (and did) modify `crtm/package.py` to install the `fix/` directory included in the tagged release. That doesn't alter the fact that there are bugs in `crtm-fix/package.py`.

**Comment by BenjaminTJohnson** [comment]
The tarball and repository fix directory are identical. 

I'll remove the offending directory from both and let you know when that's completed.  

Having said that we get active requests from collaborators who use this very same repository and tarball, so the checksums are likely to change over time.  

I'm open to recommendations on how to mitigate issues on your side -- if it simply means communicating with you when there's a change, I'm happy to do that.

**Comment by rickgrubin** [comment]
Thanks for removing the offending directory. If the repository and tarball are changing over time, it seems imperative to let @kgerheiser and @climbfuji know, as they'll be maintaining `crtm-fix`.

Perhaps [crtm@2.4.0_emc](https://github.com/JCSDA/crtm/tree/release/REL-2.4.0_emc) could not include the `fix/` directory (thus making it smaller and faster to download), but rather provide the [Get_CRTM_Binary_Files.sh](https://github.com/JCSDA/crtm/blob/release/crtm_jedi_v2.4.0/Get_CRTM_Binary_Files.sh) script, as per the JEDI-specific release:

`By default, the "fix/" directory is not provided in the CRTM. It is obtainable by running the Get_CRTM_Binary_Files.sh script.`

**Comment by climbfuji** [comment]
> Thanks for removing the offending directory. If the repository and tarball are changing over time, it seems imperative to let @kgerheiser and @climbfuji know, as they'll be maintaining `crtm-fix`.
> 
> Perhaps [crtm@2.4.0_emc](https://github.com/JCSDA/crtm/tree/release/REL-2.4.0_emc) could not include the `fix/` directory (thus making it smaller and faster to download), but rather provide the [Get_CRTM_Binary_Files.sh](https://github.com/JCSDA/crtm/blob/release/crtm_jedi_v2.4.0/Get_CRTM_Binary_Files.sh) script, as per the JEDI-specific release:
> 
> `By default, the "fix/" directory is not provided in the CRTM. It is obtainable by running the Get_CRTM_Binary_Files.sh script.`

Yes, this would be very much my preference. I'd love to get rid of the crtm-fix package in spack.

**Comment by BenjaminTJohnson** [comment]
@climbfuji @rickgrubin @kgerheiser:   I have updated the `fix/` directories for `JCSDA-internal/crtm` and `JCSDA/crtm`  `release/REL-2.4.0_emc` branch and `fix_REL-2.4.0_emc.tgz` tarball on the ftp site by removing the `J2_CRTM_Coeff_Oct31_2022/` directory entirely (it was there for convenience). 

`shasum: 206d1ff3d6410363584bc9576ad8847d908a33ad  fix_REL-2.4.0_emc.tgz`

`sha256sum: 88d659ae5bc4434f7fafa232ff65b4c48442d2d1a25f8fc96078094fa572ac1a  fix_REL-2.4.0_emc.tgz`

Please let me know if you encounter additional problems.

**Comment by climbfuji** [comment]
@rickgrubin See https://github.com/NOAA-EMC/spack/pull/195
