### ISSUE TITLE
Add gsi-ncdiag to authoritative spack

### ISSUE THREAD

**Issue by aerorahul** [JCSDA/spack#239]
### Summary

Could the gsi-ncdiag package be added to the authoritative spack repository.
https://github.com/NOAA-EMC/spack/blob/jcsda_emc_spack_stack/var/spack/repos/jcsda-emc/packages/gsi-ncdiag/package.py

### Rationale

NOAA Central Ops would like to install this package directly from the authoritative spack repository.

### Description

https://github.com/NOAA-EMC/spack/blob/jcsda_emc_spack_stack/var/spack/repos/jcsda-emc/packages/gsi-ncdiag/package.py

is added to the authoritative repository.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by climbfuji** [comment]
Closed via https://github.com/spack/spack/pull/35999
