### ISSUE TITLE
Installation issue: py-cffi on macOS with gcc+gfortran

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack#25]
### Steps to reproduce the issue

On macOS (Monterey) with gcc+gfortran installed via homebrew:
```console
$ spack install py-cffi
```

### Error message

Error is: unknown argument ```-iwithsysroot/usr/include/ffi```

### Information on your system

**WILL BE PROVIDED LATER**

### Additional information

I think I have a fix for it and will create a PR shortly

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by kgerheiser** [comment]
I was able to reproduce this.

**Comment by kgerheiser** [comment]
One thought is to force `py-cffi` to be built with Clang on macOS.

**Comment by climbfuji** [comment]
> One thought is to force `py-cffi` to be built with Clang on macOS.

I've got a simpler and less restrictive solution, and I've got one for py-scipy, too. Stay tuned.

**Comment by kgerheiser** [comment]
Fixed with #29
