### ISSUE TITLE
Installation issue: py-scipy on macOS with gcc+gfortran

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack#26]
### Steps to reproduce the issue

On macOS (Monterey) with gcc+gfortran installed via homebrew:
```console
$ spack spack install py-cffi
...
```

### Error message

The error is that the include file `threads.h` cannot be found (it doesn't exist).

### Information on your system

**WILL BE PROVIDED LATER**

### Additional information

I think I have a fix for it and will create a PR shortly.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by climbfuji** [comment]
@kgerheiser I've got a fix for that one, too, it's a little more involved than the py-cffi one. Will submit a PR once the py-cffi changes are in.

**Comment by kgerheiser** [comment]
Fixed with #30
