### ISSUE TITLE
Update spack fork from authoritative repositories (March 2022 edition) - automatic/regular updates in the future?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack#27]
### Summary

We need to update our spack fork from the authoritative repositories, it's been a few weeks since we did that.

### Description

Once this manual process is completed (there will be a few merge conflicts that I am aware of), we will need to find a way to regularly (automatically?) update and test our spack fork from the authoritative repository. It will take a long time and may not even be possible to send all our changes back to the upstream repo.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by kgerheiser** [comment]
Yeah, this would be a good idea. I wanted to get our stuff working before updating Spack. I'm thinking we try to point to official releases (+ the minimal number of changes we keep that can't be merged) as much as possible unless there's a specific update we need.

**Comment by climbfuji** [comment]
Closed via #50
