### ISSUE TITLE
INFRA-53.3: Merge spack updates into authoritative repository

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack#28]
### Summary

We have many updates to our spack fork that we should try to send back to the authoritative repository.

### Rationale

Make future management of the fork easier. I don't think it is realistic to assume that they will accept all our changes. Some of them may not be generalized easily.

We need to pick apart our changes (many of them are individual commits for individual packages, so that's good) and create upstream PRs one by one. Review and merging are very slow processes in the authoritative spack repo.

### Description

PRs:
- [x] https://github.com/spack/spack/pull/39738

### Additional information

n/a

**Comment by kgerheiser** [comment]
Yes. I did a test merge with develop a few days ago, and there were no conflicts and I think everything looks reasonable. We can remove the pnetcdf I_MPI_ROOT patch, but other than that it's all good.

**Comment by kgerheiser** [comment]
I don't know if they'll accept the lowercase variable issue. There was an issue with that where the suggested solution was to set it individually for each package and they wanted to retain the current behavior to set the vars to uppercase.

**Comment by climbfuji** [comment]
I am turning this into an epic so that we can log individual PRs that go to spack develop here. But since the spack issues don't show up in JCSDA's Zenhub, I'll keep the overall estimate of 13 story points as EPIC points and just link the PRs.

**Comment by symoore90** [comment]
I am not able to add this to the roadmap under the infra group can you please add it @climbfuji

**Comment by climbfuji** [comment]
I moved it to the epics column, thanks!

**Comment by symoore90** [comment]
Hi @climbfuji , I meant on the roadmap. If you hover over the infrastructure name a plus sign will appear on the side. Can you please add it there. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ051IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--29e6e820f8be7322ee672b2e25838f38e25ae1cc/Screenshot%202023-09-05%20at%204.11.19%20PM.png)

**Comment by climbfuji** [comment]
got it, done!

**Comment by symoore90** [comment]
Hey @climbfuji , can you take the estimate off of this epic?

**Comment by climbfuji** [comment]
> Hey @climbfuji , can you take the estimate off of this epic?

These points are there to account for previous work that didn't have any PRs with story points associated to it. The problem is that the PRs are in a repository that we don't want to connect to our Zenhub, therefore I thought this would be a good short cut rather than creating an issue in jcsda/spack-stack for every single PR that goes into the authoritative repo. Should I do that instead?

**Comment by symoore90** [comment]
Could you create an overarching issue for those PRs in JCSDA/spack-stack and connect it to this?

**Comment by climbfuji** [comment]
> Could you create an overarching issue for those PRs in JCSDA/spack-stack and connect it to this?

Hmm, this is what this epic was (an issue to collect those PRs) before it was turned into an epic.

**Comment by climbfuji** [comment]
I am going to close this as done. The work will never be complete, since we keep getting updates from spack and making updates in our fork, but we've gotten pretty good at pushing any updates we make in the fork upstream at the same time, and we've also reduced the number of differences between our fork and upstream a lot (for example by reverting our previous modifications to the module hierarchy logic). The story points assigned to this epic are a fair representation of that work.
