### ISSUE TITLE
Installation issue: cmake 3.20+ does not build with gcc on macOS

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack#33]
### Steps to reproduce the issue

On macOS with GNU gcc:
```console
$ spack install cmake@3.22.3
...
```

Not sure whether it is worth fixing this, given that after the first bug fix another, more complicated one is required. And `cmake` can easily be installed via homebrew, it doesn't get linked into the code, it's just used as a build vehicle. Therefore it doesn't matter which compiler gets used, and there are no actual dependencies on it.

### Error message

First error is related to a missing `memory.h` include, see https://github.com/NOAA-EMC/spack/pull/32. This solution is suggested directly by the compiler in the spack error log.

After fixing this, the second error is:
```
[ 85%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmLocalNinjaGenerator.cxx.o
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGContext.h:21,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBitmapContext.h:9,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h:11,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:35,
                 from /Users/dom/work/jedi-stack/spack-stack-develop-20220317/cache/build_stage/spack-stage-cmake-3.22.1-6uruyp5emkowwv3al2huqdp3hozudykb/spack-src/Source/cmGlobalXCodeGenerator.cxx:54:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:391:15: error: expected unqualified-id before '^' token
  391 | typedef void (^CGPathApplyBlock)(const CGPathElement * element);
      |               ^
...
```

### Information on your system

```
Doms-MacBook-Air:spack-stack-develop-20220317 dom$ spack debug report
* **Spack:** 0.17.1-1187-4b586ad034
* **Python:** 3.9.10
* **Platform:** darwin-monterey-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ramet** [comment]
Same trouble from my side with Mac m1 arm.

**Comment by climbfuji** [comment]
I will closet his as a "won't fix". All the work we've done in the past weeks, i.e. adding a lot of Python packages to our software stack, together with the information from the spack developers who discourage using `gcc` on macOS - especially when building Python packages -, suggest that we won't be using `gcc` on macOS in the future.
