### ISSUE TITLE
CRTM-fix@2.4.0.1 needs to copy over an additional fix file

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack#398]
### Summary

The CRTM fix file `amsua_metop-c.SpcCoeff.bin` is not copied correctly, but should be.  This file is erroneously placed in the `LittleEndian` directory, so `spack` does not copy it by default when copying big-endian files.

### Description

The same solution that is applied to `crtm-fix@2.4.0` can be applied to `crtm-fix@2.4.0.1_emc`, which copies correct file into place.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by climbfuji** [comment]
@DavidHuber-NOAA Didn't we fix this already?

**Comment by DavidHuber-NOAA** [comment]
Yes, it can be closed.
