### ISSUE TITLE
spack unit tests broken since Apr 24?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack#429]
### Steps to reproduce

See https://github.com/JCSDA/spack/actions/runs/8820831751/job/24215291345

I believe this is unrelated to changes we made - something coming from the GitHub macOS runners?

### Error message

n/a

### Information on your system

n/a

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by ChhayaKulkarni** [comment]
Hi,

I am a new user of pycrtm. I am encountering 2 kinds of errors when I run a script that calls pycrtm. 
1) Warning! amsua_metop-c.SpcCoeff.bin doesn't exist!

     **********************************************************
                            wrap_forward

      Running simulation.

      CRTM Version: v2.3.0
     **********************************************************

 SpcCoeff_ReadFile(Binary)(FAILURE) : File amsua_metop-c.SpcCoeff.bin not found.
 CRTM_SpcCoeff_Load(FAILURE) : Error reading SpcCoeff file #1, amsua_metop-c.SpcCoeff.bin
 CRTM_Init(FAILURE) : Error loading SpcCoeff data
 Error Initializing CRTM

2) Using xarray.
Killed

Could someone please explain how I can resolve this please.
