### ISSUE TITLE
Installation issue: G2 using GNU on Hera

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [JCSDA/spack#475]
### Steps to reproduce the issue

Using GNU compiler on Hera, G2 lib failed.

### Error message

```
/contrib/spack-stack/spack-stack-1.8.0/cache/build_stage/role.epic/spack-stage-g2-3.5.1-up4jxdlwolgfgjlza4lxn4c57zr6azpw/spack-src/src/g2create.F90:263:16:

  263 |   allones = int(Z'FFFFFFFF')
      |                1
Error: Arithmetic overflow converting INTEGER(16) to INTEGER(4) at (1). This check can be disabled with the option '-fno-range-check'
```

### Information on your system

spack-stack-1.8.0, GNU, Hera

### Additional information

Fixed issue by adding compile argument: -fno-range-check in spack/var/spack/repos/builtin/packages/g2/package.py file.
Pull request is coming.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by RatkoVasic-NOAA** [comment]
@AlexanderRichert-NOAA , @Hang-Lei-NOAA, @edwardhartnett
I'm creating PR right now.

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/spack-stack/pull/1287
